baseURL = "https://sergiybabich.github.io/"
languageCode = "en-us"
title = "Сергій Бабіч"
image = "123"
theme = "winston"
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = true
  addDot = true

  