baseURL = "https://sergiybabich.github.io/"
languageCode = "uk-UA"
title = "Сергій Бабіч"
image = "123"
theme = "winston"
googleAnalytics = "G-MVMXZSTYSD"
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  twitter_handle = "@babichss"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = true
  addDot = true

  